package detectors

// Java / Kotlin / Android build artifact detectors.
//
// We register the per-project `.gradle` and Maven `target` folders here;
// the global user caches (~/.gradle/caches, ~/.m2/repository) are left to
// explicit opt-in via `clearstack clean --categories=...` in Sprint 5.

func init() {
	Register(&SimpleDirDetector{
		CategoryID:    "gradle_project_cache",
		DirName:       ".gradle",
		Desc:          "Gradle per-project cache (regenerated by the wrapper)",
		SafetyLevel:   SafetySafe,
		Strategy:      StrategyTrash,
		NeedsDormancy: true,
		Require:       []string{"build.gradle"},
	})
	Register(&SimpleDirDetector{
		CategoryID:    "gradle_project_cache_kts",
		DirName:       ".gradle",
		Desc:          "Gradle per-project cache (build.gradle.kts)",
		SafetyLevel:   SafetySafe,
		Strategy:      StrategyTrash,
		NeedsDormancy: true,
		Require:       []string{"build.gradle.kts"},
	})
	Register(&SimpleDirDetector{
		CategoryID:    "maven_target",
		DirName:       "target",
		Desc:          "Maven build output (target/ with pom.xml sibling)",
		SafetyLevel:   SafetySafe,
		Strategy:      StrategyTrash,
		NeedsDormancy: true,
		Require:       []string{"pom.xml"},
	})
	Register(&SimpleDirDetector{
		CategoryID:  "android_cxx",
		DirName:     ".cxx",
		Desc:        "Android native build cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
	})
}
