package detectors

// Node / JavaScript ecosystem detectors.
//
// All of these point at regenerable artifacts and default to the Trash
// strategy. The most valuable targets (node_modules) require dormancy so we
// never touch a project the user was working on yesterday.

func init() {
	Register(&SimpleDirDetector{
		CategoryID:    "node_modules",
		DirName:       "node_modules",
		Desc:          "Node.js dependencies — regenerated by npm/yarn/pnpm/bun install",
		SafetyLevel:   SafetySafe,
		Strategy:      StrategyTrash,
		NeedsDormancy: true,
		Require:       []string{"package.json"},
	})
	Register(&SimpleDirDetector{
		CategoryID:  "next_cache",
		DirName:     ".next",
		Desc:        "Next.js build cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
		Require:     []string{"package.json"},
	})
	Register(&SimpleDirDetector{
		CategoryID:  "turbo_cache",
		DirName:     ".turbo",
		Desc:        "Turborepo local cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
	})
	Register(&SimpleDirDetector{
		CategoryID:  "nuxt_cache",
		DirName:     ".nuxt",
		Desc:        "Nuxt build cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
		Require:     []string{"package.json"},
	})
	Register(&SimpleDirDetector{
		CategoryID:  "svelte_kit_cache",
		DirName:     ".svelte-kit",
		Desc:        "SvelteKit build cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
		Require:     []string{"package.json"},
	})
	Register(&SimpleDirDetector{
		CategoryID:  "parcel_cache",
		DirName:     ".parcel-cache",
		Desc:        "Parcel bundler cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
	})
	Register(&SimpleDirDetector{
		CategoryID:  "astro_cache",
		DirName:     ".astro",
		Desc:        "Astro build cache",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
		Require:     []string{"package.json"},
	})
}
