package detectors

// Terraform / Terragrunt / OpenTofu detectors.
//
// `.terraform/` is a per-project provider+module cache that `terraform init`
// fully reconstructs in seconds. Sizes are typically 100–500 MB for non-trivial
// stacks (the AWS provider alone is ~300 MB on macOS arm64), making this one of
// the biggest reclaimable wins on a multi-project IaC machine.
//
// `.terragrunt-cache/` holds Terragrunt's cloned remote modules and download
// state. It is regenerated by `terragrunt init` / any plan/apply.
//
// Both detectors gate on a sibling Terraform source file so we never trip on
// random folders that happen to share the name. Trash strategy: matches go to
// the OS recycle bin so a misclick is recoverable via `clearstack undo`.

import (
	"context"
	"io/fs"
	"path/filepath"
)

// terraformDirDetector matches `.terraform/` only when at least one Terraform
// source file (*.tf or *.tf.json) exists in the same directory. The standard
// SimpleDirDetector cannot express "any file with extension X", so we ship a
// small specialized detector instead of bloating the helpers.
type terraformDirDetector struct{}

func (terraformDirDetector) ID() Category { return "terraform_dir" }
func (terraformDirDetector) Description() string {
	return "Terraform local cache (providers + modules — regenerated by terraform init)"
}
func (terraformDirDetector) Safety() Safety            { return SafetySafe }
func (terraformDirDetector) DefaultStrategy() Strategy { return StrategyTrash }
func (terraformDirDetector) PlatformSupported() bool   { return true }
func (terraformDirDetector) RequiresDormancy() bool    { return false }
func (terraformDirDetector) StopDescent() bool         { return true }

func (terraformDirDetector) Match(_ context.Context, path string, entry fs.DirEntry) *Match {
	if entry == nil || !entry.IsDir() || entry.Name() != ".terraform" {
		return nil
	}
	parent := filepath.Dir(path)
	if !hasTerraformSource(parent) {
		return nil
	}
	return &Match{
		Path:     path,
		Category: "terraform_dir",
		Safety:   SafetySafe,
		Strategy: StrategyTrash,
	}
}

// hasTerraformSource reports whether dir contains at least one *.tf or
// *.tf.json file (HCL or JSON Terraform syntax). Uses os.ReadDir via the
// shared lstat-cached helper to keep the cost minimal.
func hasTerraformSource(dir string) bool {
	entries, err := osReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if filepath.Ext(name) == ".tf" {
			return true
		}
		// .tf.json: the inner Ext returns ".json"; strip it and check ".tf".
		if filepath.Ext(name) == ".json" && filepath.Ext(name[:len(name)-len(".json")]) == ".tf" {
			return true
		}
	}
	return false
}

func init() {
	Register(terraformDirDetector{})

	// Terragrunt mirrors Terraform's per-project cache pattern but its
	// trigger file is terragrunt.hcl (or root.hcl in newer versions).
	Register(&SimpleDirDetector{
		CategoryID:  "terragrunt_cache",
		DirName:     ".terragrunt-cache",
		Desc:        "Terragrunt remote module cache (regenerated by terragrunt init)",
		SafetyLevel: SafetySafe,
		Strategy:    StrategyTrash,
		Require:     []string{"terragrunt.hcl"},
	})
}
